# Lab 3
### $ cd ~/iot
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/cd%20~%3Aiot.png)
### $ cd *3
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/cd%20*3.png)
### $ python3 julian.py
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/python3%20julian.png)
### $ python3 date_example.py
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/python3%20date_example.png)
### $ python3 datetime_example.py
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/python3%20datetime_example.png)
### $ python3 time_example.py
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/time_example.png)
### $ python3 sun.py "New York"
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/python3%20sun.py%20%22New%20York%22.png)
### $ python3 moon.py
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/python3%20moon.png)
### $ python3 coordinates.py "Samuel C. Williams Library"
Entering the code resulted in the following error:
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/python3%20coordinates.py%20%22Samuel%20C.%20Williams%20Library%22.png)
### $ python3 address.py "40.74480675, -74.02532861159351"
I encountered a similar error as the previous command:
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/python3%20address.py%20%2240.74480675%2C%20-74.02532861159351%22.png)
### $ python3 cpu.py
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/python3%20cpu.png)
### $ python3 battery.py
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/python3%20battery.png)
### $ python3 documentstats.py document.txt
![image](https://github.com/jamiemwai/EE-322/blob/main/Lab3Images/python3%20documentstats.py%20document.png)
